### ISSUE TITLE
[import error] ./predict evaluation/models/weights04.h5 evaluation/samples/id2_vcd_swwp2s.mpg

### ISSUE THREAD

**Issue by sanaullahmanzoor1988** [rizkiarm/LipNet#1]
I am unable to get smooth execution of code while running following line

./predict evaluation/models/weights04.h5 evaluation/samples/id2_vcd_swwp2s.mpg

Errors:
Traceback (most recent call last):
  File "/mnt/c/Users/bismil/Documents/Python Scripts/LipNet-master/evaluation/predict.py", line 1, in <module>
    from lipnet.lipreading.videos import Video
ImportError: No module named lipnet.lipreading.videos

**Comment by rizkiarm** [comment]
You need to make sure that you've installed the lipnet package.
You can do it by executing the following command on the ``LipNet-master`` folder:
```
pip install -e .
```
and make sure that every single dependency has been successfully installed.

You can check whether you have successfully installed the package by firing up python in a terminal, and typing:
```
import lipnet
```

Let me know if it resolved your problem.

**Comment by sanaullahmanzoor1988** [comment]
after executing 
         pip install -e.

I execute following

      python predict.py models/weights04.h5 samples/id2_vcd_swwp2s.mpg



Got following error (for windows 10)
File "C:\Users\bismil\AppData\Local\Programs\Python\Python35\lib\site-packages\skvideo\io\io.py", line 240, in vreader
assert _HAS_FFMPEG, "Cannot find installation of ffmpeg."
AssertionError: Cannot find installation of ffmpeg.

**Comment by sanaullahmanzoor1988** [comment]
C:\Users\bismil\Documents\Python Scripts\LipNet-master\evaluation>python predict.py models/weights04.h5 samples/id2_vcd_swwp2s.mpg
Using TensorFlow backend.

Loading data from disk...
Traceback (most recent call last):
  File "predict.py", line 46, in <module>
    video, result = predict(sys.argv[1], sys.argv[2])
  File "predict.py", line 20, in predict
    video.from_video(video_path)
  File "c:\users\bismil\documents\python scripts\lipnet-master\lipnet\lipreading\videos.py", line 119, in from_video
    frames = self.get_video_frames(path)
  File "c:\users\bismil\documents\python scripts\lipnet-master\lipnet\lipreading\videos.py", line 172, in get_video_frames
    frames = np.array([frame for frame in videogen])
  File "c:\users\bismil\documents\python scripts\lipnet-master\lipnet\lipreading\videos.py", line 172, in <listcomp>
    frames = np.array([frame for frame in videogen])
  File "C:\Users\bismil\AppData\Local\Programs\Python\Python35\lib\site-packages\skvideo\io\io.py", line 240, in vreader
    assert _HAS_FFMPEG, "Cannot find installation of ffmpeg."
AssertionError: Cannot find installation of ffmpeg.

**Comment by rizkiarm** [comment]
Those error indicates that you don't have ``ffmpeg`` installed on your system. 

Install ``ffmpeg`` on your system first and then re-run the script.

**Comment by sanaullahmanzoor1988** [comment]
ffmpeg is working

(detail view)
C:\Users\bismil\Documents\Python Scripts\LipNet-master\evaluation>ffmpeg
ffmpeg version N-85653-gb4330a0 Copyright (c) 2000-2017 the FFmpeg developers
built with gcc 6.3.0 (GCC)
configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
libavutil 55. 61.100 / 55. 61.100
libavcodec 57. 93.100 / 57. 93.100
libavformat 57. 72.101 / 57. 72.101
libavdevice 57. 7.100 / 57. 7.100
libavfilter 6. 87.100 / 6. 87.100
libswscale 4. 7.101 / 4. 7.101
libswresample 2. 8.100 / 2. 8.100
libpostproc 54. 6.100 / 54. 6.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'

**Comment by sanaullahmanzoor1988** [comment]
New Error (AttributeError: module 'skvideo.io' has no attribute 'vreader')

C:\Users\bismil\Documents\Python Scripts\LipNet-master\evaluation>python predict.py models/weights04.h5 samples/id2_vcd_swwp2s.mpg
Using TensorFlow backend.

Loading data from disk...
Traceback (most recent call last):
  File "predict.py", line 46, in <module>
    video, result = predict(sys.argv[1], sys.argv[2])
  File "predict.py", line 20, in predict
    video.from_video(video_path)
  File "c:\users\bismil\documents\python scripts\lipnet-master\lipnet\lipreading\videos.py", line 119, in from_video
    frames = self.get_video_frames(path)
  File "c:\users\bismil\documents\python scripts\lipnet-master\lipnet\lipreading\videos.py", line 171, in get_video_frames
    videogen = skvideo.io.vreader(path)
AttributeError: module 'skvideo.io' has no attribute 'vreader'

**Comment by sanaullahmanzoor1988** [comment]
After removing sk-video

Now 

executing 

python predict.py models\weights04.h5 C:\Users\bismil\Documents\Python_Scripts\LipNet-master\evaluation\samples\id2_vcd_swwp2s.mpg

and Finally its working <3 :)

thanks @rizkiarm  God bless you.

**Comment by sanaullahmanzoor1988** [comment]
After removing sk-video in python 3.5
my code working ...

because scikit-video is getting conflict with sk-video

for python 3 remove sk-video

**Comment by rizkiarm** [comment]
Glad it is working for you :)
Closed.

**Comment by GeniusJax** [comment]
I got the same problem.
When I executing:
python predict.py models\weights04.h5 C:\Users\bismil\Documents\Python_Scripts\LipNet-master\evaluation\samples\id2_vcd_swwp2s.mpg

I got  following error (for windows 10)：
File "D:\Anaconda3\lib\site-packages\skvideo\io\io.py", line 240, in vreader
    assert _HAS_FFMPEG, "Cannot find installation of ffmpeg."
AssertionError: Cannot find installation of ffmpeg.

I have installed ffmpeg too, and I still can`t fix it.
How did you resolve the problem?

**Comment by kawseribn** [comment]
@sanaullahmanzoor1988 Can you please tell me where should i write the following code:
 python predict.py models/weights04.h5 samples/id2_vcd_swwp2s.mpg
 
Because i have installed lipnet by using 
pip install -e.

Inspite of that i am getting the error:
ImportError: No module named lipnet.lipreading.videos

I am doing this on Windows

**Comment by kawseribn** [comment]
@sanaullahmanzoor1988 @rizkiarm  
Can you please help me.
after executing this:
python predict.py models/weights04.h5 samples/id2_vcd_swwp2s.mpg

I am getting nothing(no Error/ no Output) what might be the reason?

**Comment by chahatagarwal** [comment]
> @sanaullahmanzoor1988 Can you please tell me where should i write the following code:
> python predict.py models/weights04.h5 samples/id2_vcd_swwp2s.mpg
> 
> Because i have installed lipnet by using
> pip install -e.
> 
> Inspite of that i am getting the error:
> ImportError: No module named lipnet.lipreading.videos
> 
> I am doing this on Windows

So, lipnet directory is present outside evaluation directory. Hence, when you run predict.py it is not able to fetch lipnet!
