### ISSUE TITLE
Problem with extract-mouth-batch.py

### ISSUE THREAD

**Issue by jainnimish** [rizkiarm/LipNet#113]
When I try to train my own model and extract-mouth from the speaker's video, it doesn't correctly predict the face. For example, when I try to predict all the videos inside the evaluations/samples/GRID, it takes the images of the upper right corner of the face instead of the mouth. Please tell me how to fix it and why this is happening. 

Any help would be greatly appreciated. Cheers!

**Comment by Mr-Usama** [comment]
- In videos.py use these lines of code will work, using cv2 resize method occurs this problem .
from skimage.transform import resize
resized_img = resize(frame, new_img_shape)

**Comment by Mr-Usama** [comment]
> When I try to train my own model and extract-mouth from the speaker's video, it doesn't correctly predict the face. For example, when I try to predict all the videos inside the evaluations/samples/GRID, it takes the images of the upper right corner of the face instead of the mouth. Please tell me how to fix it and why this is happening.
> 
> Any help would be greatly appreciated. Cheers!

does your project works ?
