### ISSUE TITLE
Validation_steps error in train.py for random_split

### ISSUE THREAD

**Issue by AshwinPathi** [rizkiarm/LipNet#18]
I am getting an error with Keras when using the fit_generator. I tried specifying a value for "validation_steps" but it did not seem to work out.  ![screenshot from 2017-09-11 18-26-15](https://user-images.githubusercontent.com/18607510/30299737-13f26342-971f-11e7-8067-69a043bba03f.png)

**Comment by rizkiarm** [comment]
Random split is unmaintained (#2)

**Comment by AshwinPathi** [comment]
I also get the same error with unseen speakers... if that makes a difference
