### ISSUE TITLE
valueerror

### ISSUE THREAD

**Issue by crazygirl1992** [rizkiarm/LipNet#21]
ValueError: When using a generator for validation data, you must specify a value for `validation_steps`.
Found 0 videos for training.
Found 0 videos for validation.
there is trouble with" def get_video_frames(self, path):
        videogen = skvideo.io.vreader(path)"or the video form,please give me some advise,thank you!

**Comment by Yuren-Zhong** [comment]
Please refer to https://github.com/rizkiarm/LipNet/issues/22 and https://github.com/rizkiarm/LipNet/issues/23
