### ISSUE TITLE
Need help on setup

### ISSUE THREAD

**Issue by arnoldtkl** [rizkiarm/LipNet#29]
I'm installing on my macOs Serria 10.12.4. I'm using python 3.6. 
Pip version : pip 9.0.1 from /usr/local/lib/python3.6/site-packages (python 3.6)

When I run pip3 install -e .
But it show me this error. Anyone know how to fix this?

`Build using cmake ... `
`Scanning dependencies of target dlib`
`[  0%] Building CXX object dlib_build/CMakeFiles/dlib.dir/base64/base64_kernel_1.cpp.o`
`[  1%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bigint/bigint_kernel_1.cpp.o`
`[  2%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bigint/bigint_kernel_2.cpp.o`
`.....`
`[ 91%] Building CXX object CMakeFiles/dlib_.dir/src/other.cpp.o`
`/private/var/folders/c6/vl7hxs354zjfz4qdgmn258900000gn/T/pip-build-ja5_ssrg/dlib/tools/python/src/other.cpp:56:1: error: reference to 'list' is ambiguous`
    `list _max_cost_assignment (`
    `^`
   ` /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/list:777:29: note: candidate found by name lookup is 'std::__1::list'`
    `class _LIBCPP_TYPE_VIS_ONLY list`
                                `^`
    `/usr/local/include/boost/python/list.hpp:57:7: note: candidate found by name lookup is 'boost::python::list'`
    `class list : public detail::list_base`
          `^`
    `/private/var/folders/c6/vl7hxs354zjfz4qdgmn258900000gn/T/pip-build-ja5_ssrg/dlib/tools/python/src/other.cpp:72:11: error: reference to 'list' is ambiguous`
        `const list& assignment`
              `^`
    `/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/list:777:29: note: candidate found by name lookup is 'std::__1::list'`
    `class _LIBCPP_TYPE_VIS_ONLY list`
                                `^`
    `/usr/local/include/boost/python/list.hpp:57:7: note: candidate found by name lookup is 'boost::python::list'`
    `class list : public detail::list_base`
          `^`
    `2 errors generated.`
    `make[2]: *** [CMakeFiles/dlib_.dir/src/other.cpp.o] Error 1`
    `make[1]: *** [CMakeFiles/dlib_.dir/all] Error 2`
    `make: *** [all] Error 2`
   ` error: cmake build failed!`

**Comment by optimisth** [comment]
same problem. need help please..

**Comment by sf308** [comment]
I'm having exactly the same problem!

**Comment by arnoldtkl** [comment]
I remove all the version of setup.py

`	install_requires=[`
      `  'Keras',`
       ` 'editdistance',`
		`'h5py',`
		`'matplotlib',`
		`'numpy',`
		`'python-dateutil',`
		`'scipy',`
		`'Pillow',`
		`'tensorflow',`
		`'Theano',`
        `'nltk',`
       ` 'sk-video',`
       ` 'dlib'`
  `  ])`

This seems work for me.
