### ISSUE TITLE
ValueError: Dimension 0 in both shapes must be equal, but are 512 and 256 for 'Assign_12' (op: 'Assign') with input shapes: [512,768], [256,768].

### ISSUE THREAD

**Issue by Foursmall** [rizkiarm/LipNet#3]
when I run the default demo with command "./predict evaluation/models/weights04.h5  evaluation/samples/id2_vcd_swwp2s.mpg ",Error"ValueError: Dimension 0 in both shapes must be equal, but are 512 and 256 for 'Assign_12' (op: 'Assign') with input shapes: [512,768], [256,768]."happened.
Could you tell me resolution ?Thank you sincerely!

**Comment by FredlinT** [comment]
I meet with the same problem as you@Foursmall

**Comment by rizkiarm** [comment]
I've updated the example weight. It should be working now.
I'll close this issue. Just reopen if it doesn't work for you.
