### ISSUE TITLE
Error Loading video

### ISSUE THREAD

**Issue by sf308** [rizkiarm/LipNet#36]
Have any of you experienced this problem? I was compliling training data for s1, s2 and s3 for random_split using the command ./train random_split but I am getting responses saying "error loading video". 
![capture](https://user-images.githubusercontent.com/1135588/34889712-f2c34cfa-f7c6-11e7-939c-cc93a86aa35a.PNG)

I recently added the following line to RandomSplitGenerator in the train.py file to solve the size issue:
"vtype = "face", face_predictor_path='home\souheil\LipNet\common\predictors\shape_predictor_68_face_landmarks.dat',"

However I am still experiencing errors. Have any of you experience this problem?

**Comment by sf308** [comment]
I've realised that I am getting an error saying in another script saying "Unable to open home/souheil/LipNet/common/predictors/shape_predictors/shape_predictor_68_face_landmarks.dat" so this may be the problem.

**Comment by sf308** [comment]
Problem sorted!

**Comment by bouayad** [comment]
may i know how did you solve the problem?

**Comment by gzz666** [comment]
@sf308 ,Hey,can you tell me how to solve this problem? thanks
