### ISSUE TITLE
User worning

### ISSUE THREAD

**Issue by Adam-Oudaimah** [rizkiarm/LipNet#41]
i am having the following issue:
Update your `fit_generator` call to the Keras 2 API
What should i do about it?
I know i am asking a lot, but i am working on a graduation project about lip readign
please if any one could help me.
Thanks a lot

**Comment by dimaxano** [comment]
Try to use these names of the arguments to the fit_generator
`
lipnet.model.fit_generator(generator=lip_gen.next_train(),
                        steps_per_epoch=lip_gen.default_training_steps, epochs=stop_epoch,
                        validation_data=lip_gen.next_val(), validation_steps=lip_gen.default_validation_steps,
                        callbacks=[checkpoint, statistics, visualize, lip_gen, tensorboard, csv_logger], 
                        initial_epoch=start_epoch, 
                        verbose=1,
                        use_multiprocessing=True,
                        max_queue_size=5,
                        workers=4)
`

**Comment by rizkiarm** [comment]
It's okay, it is just a warning.
