### ISSUE TITLE
about abstract the image feature

### ISSUE THREAD

**Issue by crazygirl1992** [rizkiarm/LipNet#43]
hello,my research is related to the lipnet,now t want to get the features from this code with 3Dcnn, now i can run the code,but i dont know how to get the lip features.can you give me some tips? @rizkiarm @michiyosony

**Comment by rizkiarm** [comment]
Please check this Keras FAQ:
https://keras.io/getting-started/faq/#how-can-i-obtain-the-output-of-an-intermediate-layer

Hope it helps!
