### ISSUE TITLE
about grid dataset

### ISSUE THREAD

**Issue by crazygirl1992** [rizkiarm/LipNet#45]
hello,now i want run the code with my dataset,but i don't know the grid dataset's text 
0 14000 sil
14000 19750 bin
19750 25000 blue
25000 30250 by
30250 38750 s
38750 49000 five
49000 61000 please
61000 74500 sil
the data before the word means what,and how can i change my data to train the code?thank you @rizkiarm @michiyosony

**Comment by michiyosony** [comment]
The first number indicates the start of that word.  The second number indicates the stop.  I couldn't find a source for this, but it appears that they are frame numbers x 1000.  So frames 0-14 are silence, frames 14-20 are the word "bin", etc.

**Comment by rizkiarm** [comment]
@michiyosony is correct. Please do visit their website for more details: http://spandh.dcs.shef.ac.uk/gridcorpus/
