### ISSUE TITLE
Are there any pre-trained models?

### ISSUE THREAD

**Issue by Adam-Oudaimah** [rizkiarm/LipNet#50]
Please Help.
My computer is too old, i could not do any training.
are there any pre-trained models you can help me with?
Even if the accuracy is too bad, i need it for my graduation project.
Just to prove the concept.
thanks a lot.

**Comment by rizkiarm** [comment]
There are pre-trained models but wasn't specified in the README. 

Please check the updated readme here:
https://github.com/rizkiarm/LipNet#pre-trained-weights

Hope it helps!
