### ISSUE TITLE
Getting Loading dataset list from cache... Found 0 videos for training. Found 0 videos for validation.

### ISSUE THREAD

**Issue by kpkool1995** [rizkiarm/LipNet#51]
Hi,

Can anyone help me as I am getting the following error while training the model from train.py

Loading dataset list from cache...
Found 0 videos for training.
Found 0 videos for validation.

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
the_input (InputLayer)       (None, 75, 100, 50, 3)    0
_________________________________________________________________
zero1 (ZeroPadding3D)        (None, 77, 104, 54, 3)    0
_________________________________________________________________
conv1 (Conv3D)               (None, 75, 50, 25, 32)    7232
_________________________________________________________________
batc1 (BatchNormalization)   (None, 75, 50, 25, 32)    128
_________________________________________________________________
actv1 (Activation)           (None, 75, 50, 25, 32)    0
_________________________________________________________________
spatial_dropout3d_1 (Spatial (None, 75, 50, 25, 32)    0
_________________________________________________________________
max1 (MaxPooling3D)          (None, 75, 25, 12, 32)    0
_________________________________________________________________
zero2 (ZeroPadding3D)        (None, 77, 29, 16, 32)    0
_________________________________________________________________
conv2 (Conv3D)               (None, 75, 25, 12, 64)    153664
_________________________________________________________________
batc2 (BatchNormalization)   (None, 75, 25, 12, 64)    256
_________________________________________________________________
actv2 (Activation)           (None, 75, 25, 12, 64)    0
_________________________________________________________________
spatial_dropout3d_2 (Spatial (None, 75, 25, 12, 64)    0
_________________________________________________________________
max2 (MaxPooling3D)          (None, 75, 12, 6, 64)     0
_________________________________________________________________
zero3 (ZeroPadding3D)        (None, 77, 14, 8, 64)     0
_________________________________________________________________
conv3 (Conv3D)               (None, 75, 12, 6, 96)     165984
_________________________________________________________________
batc3 (BatchNormalization)   (None, 75, 12, 6, 96)     384
_________________________________________________________________
actv3 (Activation)           (None, 75, 12, 6, 96)     0
_________________________________________________________________
spatial_dropout3d_3 (Spatial (None, 75, 12, 6, 96)     0
_________________________________________________________________
max3 (MaxPooling3D)          (None, 75, 6, 3, 96)      0
_________________________________________________________________
time_distributed_1 (TimeDist (None, 75, 1728)          0
_________________________________________________________________
bidirectional_1 (Bidirection (None, 75, 512)           3048960
_________________________________________________________________
bidirectional_2 (Bidirection (None, 75, 512)           1181184
_________________________________________________________________
dense1 (Dense)               (None, 75, 28)            14364
_________________________________________________________________
softmax (Activation)         (None, 75, 28)            0
=================================================================
Total params: 4,572,156
Trainable params: 4,571,772
Non-trainable params: 384
_________________________________________________________________
train.py:69: UserWarning: Update your `fit_generator` call to the Keras 2 API: `fit_generator(generator=<lipnet.he..., steps_per_epoch=0.0, epochs=20, validation_data=<lipnet.he..., validation_steps=0.0, callbacks=[<keras.ca..., initial_epoch=0, verbose=1, workers=2, use_multiprocessing=False, max_queue_size=5)`
  pickle_safe=False)
Traceback (most recent call last):
  File "train.py", line 73, in <module>
    train(run_name, 0, 20, 3, 100, 50, 75, 32, 50)
  File "train.py", line 69, in train
    pickle_safe=False)
  File "C:\Users\karan.kumar.panda\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\karan.kumar.panda\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 2107, in fit_generator
    raise ValueError('`validation_steps=None` is only valid for a'
ValueError: `validation_steps=None` is only valid for a generator based on the `keras.utils.Sequence` class. Please specify `validation_steps` or use the `keras.utils.Sequence` class.

**Comment by liviust** [comment]
Check the symlinks.

**Comment by gzz666** [comment]
Hey,can you let me see your folders? I do not understand how to create symlink

**Comment by DerekChia** [comment]
Did you follow the instruction?

> ### Overlapped Speakers
> Run the preparation script:
> ```
> python prepare.py [Path to video dataset] [Path to align dataset] [Number of samples]
> ```
> **Notes:**
> - ``[Path to video dataset]`` should be a folder with structure: ``/s{i}/[video]``
> - ``[Path to align dataset]`` should be a folder with structure: ``/[align].align``
> - ``[Number of samples]`` should be less than or equal to ``min(len(ls '/s{i}/*'))``
> 
> Then run training for each speaker:
> ```
> python training/overlapped_speakers/train.py s{i}
> ```
>

**Comment by gzz666** [comment]
yes,thanks!however ,I have other issue.
ValueError: output of generator should be a tuple `(x, y, sample_weight)` or `(x, y)`. Found: None
I do not know how to solve it
Do you know?

**Comment by DerekChia** [comment]
> yes,thanks!however ,I have other issue.
> ValueError: output of generator should be a tuple `(x, y, sample_weight)` or `(x, y)`. Found: None
> I do not know how to solve it
> Do you know?

I also getting this error and trying to fix it now. If you'd like to solve it together, can you please contact me via my email (see profile), thanks!

**Comment by kawseribn** [comment]
@DerekChia can you show me how should i put folders? i am also facing probelm regarding symlink.
Though i saw their attached description but its not clear to me.
