### ISSUE TITLE
What are the parameters in train(run_name, 0, 5000, 3, 100, 50, 75, 32, 50).

### ISSUE THREAD

**Issue by kpkool1995** [rizkiarm/LipNet#53]
Hi All,
Can someone point out what is the significance of the parameters in train(**run_name, 0, 5000, 3, 100, 50, 75, 32, 50**) training/unseen_speakers/train.py.

Thanks in advance :)

**Comment by kokosowygosc** [comment]
train(run_name, start_epoch, stop_epoch, img_c, img_w, img_h, frames_n, absolute_max_string_len, minibatch_size) :)

**Comment by rizkiarm** [comment]
I will close this issue. Please re-open the issue (or create a new one) if you have some more problems.

**Comment by kpkool1995** [comment]
Hey, Reopening the issue and rephrasing my question further.
What is the significance of parameters in train(run_name, 0, 5000, 3, 100, 50, 75, 32, 50).
I meant if I need my own training videos, what these parameters would be?

Thanks for the reply, hope I will get the apt reply this time.

**Comment by rizkiarm** [comment]
Please read https://github.com/rizkiarm/LipNet#prerequisites, and specify the properties of your new training dataset to the ``train`` method according to this specification:
```
train(run_name, start_epoch, stop_epoch, img_c, img_w, img_h, frames_n, absolute_max_string_len, minibatch_size)
```
