### ISSUE TITLE
What is the significance of the parameters in train(run_name, 0, 5000, 3, 100, 50, 75, 32, 50).

### ISSUE THREAD

**Issue by kpkool1995** [rizkiarm/LipNet#57]
Hi, it would be great for an urgent reply.
What is the significance of parameters in train(run_name, 0, 5000, 3, 100, 50, 75, 32, 50).
I meant if I need my own training videos, what these parameters would be?

Thanks in advance....

**Comment by rizkiarm** [comment]
Duplicate (https://github.com/rizkiarm/LipNet/issues/53)
