### ISSUE TITLE
ValueError: `validation_steps=None` is only valid for a generator based on the `keras.utils.Sequence` class. Please specify `validation_steps` or use the `keras.utils.Sequence` class.

### ISSUE THREAD

**Issue by gzz666** [rizkiarm/LipNet#76]
Loading dataset list from cache...
Found 0 videos for training.
Found 0 videos for validation.
   raise ValueError('`validation_steps=None` is only valid for a'
ValueError: `validation_steps=None` is only valid for a generator based on the `keras.utils.Sequence` class. Please specify `validation_steps` or use the `keras.utils.Sequence` class

symlink has been created，but it still has error

**Comment by graycell666** [comment]
Hey, have you received "Error loading video:"+path?
If you have, you may have the same problem as I do.
I have something wrong while running "skvideo.io.vreader".
I used "sudo apt-get install ffmpeg" to solve the problem.

**Comment by gzz666** [comment]
> Hey, have you received "Error loading video:"+path?
> If you have, you may have the same problem as I do.
> I have something wrong while running "skvideo.io.vreader".
> I used "sudo apt-get install ffmpeg" to solve the problem.



> Hey, have you received "Error loading video:"+path?
> If you have, you may have the same problem as I do.
> I have something wrong while running "skvideo.io.vreader".
> I used "sudo apt-get install ffmpeg" to solve the problem.

**Comment by gzz666** [comment]
@graycell666 Hey, I have not received"Error loading video:"+path.
But I may know that my mistake is that I didn't  understand the readme and created the wrong folder.I am using github for the first time.Can you show me how you created the folder based on the readme? thank you very much.

**Comment by graycell666** [comment]
@gzz666 Take the unseen_speakers as an example, after the symlink, my path is:
`/LipNet/training/unseen_speakers/datasets/train/s*/*.mpg`
`/LipNet/training/unseen_speakers/datasets/val/s*/*.mpg`
`/LipNet/training/unseen_speakers/datasets/align/*.align`
I'm also new and I haven't trained yet because of some other problems, but maybe you can try create the folder like this.

**Comment by gzz666** [comment]
我的路径和你的弄得一样。但是还是加载不了video。我想知道你是怎么创建sylink的。是在终端   ln  -s  xx   xx还是直接把数据放到文件夹里的啊？

**Comment by graycell666** [comment]
是在终端使用 ln -s

**Comment by gzz666** [comment]
你也是大学生吗？我这个是做毕业设计的。你也是吗？我就是用的终端弄得，结果就是不出来。崩溃！可以留个QQ或者微信嘛？方便一起讨论学习这个项目。我的QQ是2689226201。😂️😂️😂️
