### ISSUE TITLE
GPU training

### ISSUE THREAD

**Issue by Zhaans** [rizkiarm/LipNet#85]
Hello,

I am trying to train overlapped_speakers on GPU. However I cannot see any GPU usage, although I installed tensorflow-gpu and can see message:

```
> Using all available GPUs.
> Using TensorFlow backend.
```
On CPU everything is fine.
Any suggestions? Thanks!

**Comment by RifqiAW** [comment]
Try running the train.py directly without using the script

python3 train.py

It worked for me.

**Comment by Zhaans** [comment]
> Try running the train.py directly without using the script
> 
> python3 train.py
> 
> It worked for me.

Thanks for your answer. How much GPU memory does it take? And for what scenario are you training?

**Comment by RifqiAW** [comment]
10 gb I think? I used batch size 64, just reduce the size if it doesn't fit. And I tested it for the unseen_speakers scenario. And also just a heads up if you got memory leaks during training then you might want to implement your own generators or at least tweaked the current one.

**Comment by Zhaans** [comment]
> 10 gb I think? I used batch size 64, just reduce the size if it doesn't fit. And I tested it for the unseen_speakers scenario. And also just a heads up if you got memory leaks during training then you might want to implement your own generators or at least tweaked the current one.

Ok, got it, will try it. Thanks a lot for your quick reply!

**Comment by njan-creative** [comment]
@rizkiarm Can you let me know the hardware used to train this model and the training time..
